Noxime/steamworks-rs

src/error.rs
src/friends.rs
src/matchmaking.rs
src/server.rs
src/ugc.rs
src/user_stats.rs
src/utils.rs
steamworks-sys/src/lib.rs

...plus a few other tweaks like struct derivations and method signatures.

binding for SetLobbyJoinable

---

src/ugc.rs

Also `impl From<sys::EWorkshopFileType> for FileType`

Add `file_type` to UGC `QueryResult`

---

src/ugc.rs

This is needed because a `SteamError` does not provide enough information about the download, such as the app id of the download, which is crucial for actually figuring out if the download that failed was your download, or another app's!

Change `Result<DownloadItemResult, SteamError>` -> `DownloadItemResult`

---

steamworks-sys/build.rs

Moves copying the SDK files to before creating bindings, and moves the rustc-link-search to point to OUT_DIR, which should point to inside the target dir.
This should allow `cargo run` to work with STEAM_SDK_LOCATION values that are outside the target dir.
Fixes #55.

Fix #55: Move rustc-link-search to target dir

---

src/matchmaking.rs

Add a method for getting a lobby's member limit
Add a method for getting a lobby's metadata associated with a key
Additionally, format matchmaking.rs using rustfmt

Provide additional useful Matchmaking methods

---

src/matchmaking.rs

After this change, I was able to monitor use updates in the lobby room:
```rust
let _cb = client.register_callback({
move |p: LobbyChatUpdate| {
println!("Got LobbyChatUpdate callback: {:?}", p);
match p.member_state_change {
ChatMemberStateChange::Entered => {
println!("User {:?} entered", p.user_changed);
},
ChatMemberStateChange::Left => {
println!("User {:?} left", p.user_changed);
},
_ = {}
}
}
});
```
Not sure where `LobbyChatUpdate` belongs, but it works!

Add LobbyChatUpdate

---

src/networking_types.rs

There is a bug that the project doesn't build when serde feature isn't enabled.

Fix build when serde feature is enabled

---

src/input.rs
src/lib.rs

Add ISteamInput implementation

---

Cargo.toml
src/lib.rs
src/matchmaking.rs
src/networking_sockets.rs
src/remote_storage.rs
src/server.rs
src/user.rs
src/user_stats.rs

And so remove the `serial_test_derive` dependency

Can get to serial_test_derive via serial_test

---

src/user.rs

This is enough to make the microtransactions flow to work. Would also be nice to have https://partner.steamgames.com/doc/api/ISteamInventory#StartPurchase implemented.

Add MicroTxnAuthorizationResponse callback

---

src/callback.rs

Fixes https://github.com/Noxime/steamworks-rs/issues/124

add callback disconnect method to replace drop

---

src/friends.rs

Add activate_game_overlay_to_store and activate_game_overlay_to_user

---

src/friends.rs
src/utils.rs

Hello,
I have added the callback for [GameOverlayActivated_t](https://partner.steamgames.com/doc/api/ISteamFriends#GameOverlayActivated_t)
I could have passed the "active" as a boolean, but I preferred to stick to the steam api, tell me if I should change it.

added GameOverlayActivated Callback

---

src/input.rs

Hope this is ok, I wasn't able to get tests working locally, please let me know if there's something more I need to do

Add controler helper bindings

---

src/server.rs

I struggled with this for 2 days lol. How can this typo be here for 5 years

fix set_server_name calling SetMapName

---

src/networking_messages.rs

The return value is useful and should be exposed.

Added a return value to AcceptSessionWithUser

---

src/networking.rs

fixes #216 
keeps the existing methods that just wrap the new ones that expose the channel argument for backwards compatibility with existing code

expose channel arg for p2p `ISteamNetworking` methods

---

src/input.rs

Fix unsound use of unsafe in get_connected_controllers

---

src/matchmaking.rs

I found that `add_request_lobby_list_string_filter` is not working, so I fixed it

Fix matchmaking filters.

---

src/callback.rs
src/friends.rs
src/lib.rs

Closes #230 by @vs-andresfranco
There was a little change I wanted to do, but couldn't push to the PR branch.

Add GameRichPresenceJoinRequested

---

src/remote_storage.rs

Implement Get/SetSyncPlatforms

---

src/remote_storage.rs

file sharing doesn't seem to be used much, but can be useful for certain games/tools, so this adds the relevant method
for future reference to anyone looking for information—file share URLs follow the following format:
- call ISteamRemoteStorage::FileShare, the u64 it returns becomes `id`
- take the SHA1 hash of the file's contents, convert that to little-endian ordered uppercase hexadecimal which becomes `sha1`
- `format!("https://steamusercontent-a.akamaihd.net/ugc/{id}/{sha1}/")` (note the trailing slash is *required*
example code utilizing this, [sha1](https://crates.io/crates/sha1), and [hex](https://crates.io/crates/hex):
```rust
let fi = steam.remote_storage().file(file);
// ask steam for the share ID
let id = fi.share().unwrap();
// read the file bytes
let mut reader = fi.read(); …
```

implement ISteamRemoteStorage::FileShare
