steamworks-sys/build.rs

This pr removes fields with enum types containing `::`.
The build currently skips generation of enums containing `::`, so this allows the built code to compile when they exist in the steam api's json. Ie the new code matches the existing:
```rust
for e in steam_api.enums {
if e.enumname.contains("::") {
continue;
}
...
```
Maybe there's a better fix, this is just how I got it to compile.

Skip fields with missing enum types

---

src/user_stats.rs
src/user_stats/stat_callback.rs
src/user_stats/stats.rs
steamworks-sys/build.rs
steamworks-sys/src/lib.rs

This pr adds wrappers for the achievements flow:
* `RequestCurrentStats`
* `{Get,Set,Clear}Achievement`
* `StoreStats`
Plus associated callback types. I also fixed some `c_char` binding issues as a new callback includes a `c_char` array.
I'll be using this API in Robo Instructus.
```rust
let user_stats = client.user_stats();
user_stats.request_current_stats();
// run callbacks
user_stats.achievement("WIN_THE_GAME").set()?;
user_stats.store_stats()?;
```

Add stats & achievements API

---

Cargo.toml
src/lib.rs
src/ugc.rs
src/utils.rs
steamworks-sys/src/lib.cpp
steamworks-sys/src/lib.rs

Supported major features are (un)subscribing from items, getting the list of currently subscribed items, and performing searches against user-related lists (ex. currently subscribed, favorited, ...) for the current app. Can be extended to other searches later.
Also adds a few other things I found useful: `SteamId::account_id` and `Utils::set_warning_callback`.

Partial UGC (Workshop) Support

---

Cargo.toml
src/app.rs
src/lib.rs
src/matchmaking.rs
src/remote_storage.rs
src/server.rs
src/user.rs
src/user_stats.rs
steamworks-sys/build.rs

I don't know why it worked for you and not me but I'm guessing it's because Valve released a new version of their SDK: `v1.45 25th June 2019`. Whatever it is that changed, I updated the build script so it works on all 3 target platforms now. There were 3 main issues:
* The C++ source code wouldn't compile on Unix without C++11 explicitly enabled.
* The compiled code couldn't find "libsteam_api.dll" (or .so or .dylib) so the solution I found was to just copy it into the output directory. If there's a better way to do this, I'd like to hear it.
* Steamworks doesn't have an "osx64" folder anymore. They renamed it to "osx" I assume because Apple dropped support for 32-bittiness.
I also added the `serial_test` derive macros to make all of the tests run sequentially instead of in parallel …

Update build script

---

Cargo.toml
src/app.rs
src/callback.rs
src/error.rs
src/friends.rs
src/lib.rs
src/matchmaking.rs
src/networking.rs
src/remote_storage.rs
src/server.rs
src/ugc.rs
src/user_stats.rs
src/utils.rs

I needed to send messages through an API that only works on byte buffers. Instead of wrapping everything in newtypes, it's better if oldtypes implement common interfaces. (More detailed guidelines here https://rust-lang-nursery.github.io/api-guidelines/interoperability.html but that's the basic gist of it.)
Also fixed some minor issues: formatting, typos, redundant cast.

Added serde traits and other common traits

---

src/ugc.rs

Also a question: why do these functions take `self` instead of `&self`?

Add UpdateHandle description and preview

---

Cargo.toml
src/error.rs
src/lib.rs
src/user.rs

As per [this](https://rustsec.org/advisories/RUSTSEC-2020-0036.html) advisory, the `failure` crate will no longer be maintained. I've replaced `failure` with `thiserror`, which `failure` recommends as a drop-in replacement for deriving `Display` impls for Error types.

Replace failure with thiserror

---

src/friends.rs

For some reason Steamworks docs says this is 128x128 but it's 184x184 ¯\\\_(ツ)_/¯

Add friends::large_avatar (binding to ISteamFriends->GetLargeFriendAvatar)

---

src/ugc.rs

Also fixed a redundant cast and a doc typo.

Add QueryResults::preview_url to get preview URL of a UGC published file from QueryResults

---

src/ugc.rs

Merge conflict fix for my other PR #32 
```rust
/// Gets a UGC statistic about the published file at the specified index.
pub fn statistic(&self, index: u32, stat_type: UGCStatisticType) -> Option<u64> {
let mut value = 0u64;
let ok = unsafe {
sys::SteamAPI_ISteamUGC_GetQueryUGCStatistic(self.ugc, self.handle, index, stat_type.into(), &mut value)
};
debug_assert!(ok);
if ok {
Some(value)
} else {
None
}
}
/// Gets the preview URL of the published file at the specified index.
pub fn preview_url(&self, index: u32) -> Option<String> {
let mut url = [0 as libc::c_char; 4096];
let ok = unsafe {
sys::SteamAPI_ISteamUGC_GetQueryUGCPreviewURL(self.ugc, self.handle, index, url.as_mut_ptr(), url.len() as _)
};
if ok {
Some(unsafe {
CStr::from_ptr(url.as_ptr() as *const _)
.to_string_lossy() …
```

Add steamworks::UGCStatisticType and add QueryResults::statistic (bindings for ISteamUGC::GetQueryUGCStatistic)

---

src/ugc.rs

Also improved safety of ugc::query_user
The code duplication kind of smells, I wanted to use a trait for it instead but traits can't reference struct fields yet, so this will have to do.

Add ugc::query_items and ugc::query_item for querying specific PublishedFileId(s)

---

steamworks-sys/Cargo.toml
steamworks-sys/build.rs
steamworks-sys/src/lib.rs

This PR makes cargo rebuild the `sys` crate whenever `STEAM_SDK_LOCATION` changes, which helps solve some of the issues from #37. 
I also updated the crate to edition 2018 since that only required adding the appropriate line in the `Cargo.toml` and removing all `extern <crane-name>`s from `lib.rs`. I also removed `libc` from the `sys` crate since I don't think it was doing anything as its types were never re-exported. 
Looking over the library as a whole, I think it would be fairly trivial to remove the `libc` dependency entirely in favor of relying on std types. I can add it to this PR or create a new one if this is desired.

Rebuild `sys` crate whenever `STEAM_SDK_LOCATION` changes

---

src/friends.rs

Returns the bool from RequestUserInformation signifying if the data is already immediately available or not.

Make request_user_information return the returned bool from Steamworks

---

src/ugc.rs

Resolves the problem when ugc::query_items returns an invalid result amongst its other results which causes a panic with ugc::QueryResults::iter.
I guess it's for backwards compatibility so we don't need to change ugc::QueryResults::iter.

Add ugc::QueryResults::iter_maybe

---

Cargo.toml
src/callback.rs
src/friends.rs
src/lib.rs
src/networking.rs
src/ugc.rs
src/user.rs
src/user_stats/stat_callback.rs
src/utils.rs

As mentioned in #38, I tried to remove the `libc` dependency entirely from this library. This ended up being extremely straightforward, as the stdlib contains types that have a 1-1 correspondence with the used `libc` types.

Remove `libc` dependency

---

src/ugc.rs

Useful for mapped iterators and convenient type conversion.

Add `From<u64>` for `PublishedFileId`

---

src/ugc.rs

Returns a list of PublishedFileIds for the query result at the given index.
Useful for querying collections or item dependencies.

Add `QueryResults::get_children`

---

src/user.rs

Have tested that they work - you can't just set your friends status as offline to test these callbacks, the Steam servers connection persists. Turning off your computer's networking executes the callbacks.

Add `SteamServersConnected`, `SteamServersDisconnected` and `SteamServerConnectFailure` callbacks

---

src/ugc.rs

Useful for chunking paginated results.

Export `sys::kNumUGCResultsPerPage`

---

steamworks-sys/build.rs

Steamworks needs C++11 and clang by default uses 98 iirc

Fix macOS builds

---

src/app.rs
src/lib.rs

This allows you to specify an `AppId` manually, removing the need to include `steam_appid.txt` with your application.

Add `Client::init_app()` which removes the need for `steam_appid.txt`

---

src/friends.rs

Adding `set_rich_presence` function, initially [here](https://partner.steamgames.com/doc/api/ISteamFriends#SetRichPresence).
This is a pretty straightforward function that receives two strings and returns a boolean.
Tested by calling this function and getting a `true` response, though to be honest this wasn't reflected on the [test URL](https://steamcommunity.com/dev/testrichpresence).

Add set_rich_presence

---

src/lib.rs

As described in [the tracking issue](https://github.com/rust-lang/rust/issues/82523), taking a reference to a field in a packed struct can cause UB.  Copying the field's value when possible is preferred.

Fix unaligned reference

---

Cargo.toml
src/lib.rs

I have found myself needing this on multiple occasions and it's nice that steamworks-rs already has all the bindings generated for us.

Add `raw-bindings` feature which exports `sys`

---

src/user_stats.rs

This adds wrappers for getting leaderboard display_type, sort_method,
name, entry_count, and the raw id.

Adds support for more UserStats Leaderboards functions

---

src/lib.rs
src/networking_messages.rs
src/networking_types.rs

Starting with `SteamNetworkingMessages` initially which has a much smaller API surface and is almost completely compatible with the message based API in `SteamNetworking`. I've opened this PR as a draft for any early feedback on the Rust wrapping, but there's still a lot to do.

[wip] Support newer Steam networking interfaces

---

.github/workflows/ci.yml
examples/chat-example/src/main.rs
rustfmt.toml
src/app.rs
src/callback.rs
src/error.rs
src/friends.rs
src/lib.rs
src/networking.rs
src/networking_sockets.rs
src/networking_utils.rs
src/remote_storage.rs
src/server.rs
src/ugc.rs
src/user.rs
src/user_stats.rs
src/user_stats/stats.rs
src/utils.rs

This PR adds GitHub Actions that check the code format for `steamworks`, and set a rustfmt.toml to ignore `steamworks-sys`, as it's generated code. Also ran a `cargo fmt --all` over the codebase.

Enable formatting checks in CI

---

src/utils.rs

This pull request adds a function `Utils::get_server_real_time() -> u32`. It's a very simple PR.
I needed this for Final Fantasy XIV stuff.

Add Steam server time function

---

Cargo.toml
README.md
steamworks-sys/Cargo.toml

With the changes in how `steamworks-sys` is linked, and several other changes that had been introduced since the last version, it's probably time to release a new version of the crate.
In this PR:
- Updated edition to 2021.
- Bumped outdated dev-dependencies
- Bumped crate version to v0.9.0.

Release: v0.9.0

---

src/remote_storage.rs
src/ugc.rs

This PR adds support for setting the visibility of uploaded UGC files. The newly implemented enum may find implementation in a couple more spots, though I didn't check that.

Add missing UpdateHandle functions

---

src/networking_sockets.rs
src/networking_types.rs

I couldn't find anything explicit in the steamworks documentation, so I'm assuming that unreliable messages can also be unordered. This way, it's easy to check which message was received first.

Make networking_types::MessageNumber more convenient to use

---

src/input.rs

I've split logical changes into their own commits but made a single PR in the interest of reducing PR spam.
The first commit is the most critical, it fixes a potential buffer overflow issue. I can only imagine that this was the intended behavior. I can split that out into a separate PR if the rest is not immediately ready to be accepted.

Misc changes to Input bindings.

---

Cargo.toml
examples/workshop/Cargo.toml
examples/workshop/README.md
examples/workshop/src/main.rs

As mentioned in #101 , this is an extended example for operating the UGC API in order to manage workshop items.

Added example for creating, uploading and deleting workshop items

---

src/utils.rs

I added some missing ISteamUtils functions required for the Steam Deck:
* IsSteamRunningOnSteamDeck
* GetEnteredGamepadTextInput
* GetEnteredGamepadTextLength
* ShowGamepadTextInput
* ShowFloatingGamepadTextInput
I haven't tested these yet, so I'd appreciate it if @gemdude46 could test them, since they asked for them in #118 . Especially `GetEnteredGamepadTextInput`, since it requires to be called in a specific callback (`GamepadTextInputDismissed_t` and I presume `FloatingGamepadTextInputDismissed_t` has that requirement too).
For ease of use, I added callback parameters to `show_gamepad_text_input` and `show_floating_gamepad_text_input` which trigger respectively when the gamepads have been dismissed, that should make it safe to get the text inside those callbacks.

Add some missing ISteamUtils functions required for the Steam Deck

---

src/app.rs

This is needed in order to join through steam rich presense (without warnings) for instance.

Add `Apps::launch_command_line`

---

src/user.rs

A small change to expose the `ISteamUser::BLoggedOn()` function via the `User` struct.

Add User::logged_on

---

src/networking_sockets.rs
src/networking_types.rs

This pr fixes #133.
The goal of this PR is to get a way to identify if a NetworkConnection is still valid and to get its connection state.
**Motivation**
As a user or server/host i want to be able to know in which state the connection is, so that i can react on this changes.
**Example**
In Bevy i only want to run the systems for a connecting state when im in the connection state like a loading screen.
And also systems for Connecting and Disconnecting.
**Tasks**

Add method GetConnectionInfo

---

src/matchmaking.rs

closes #137
summary:
* renamed SendLobbyChatMsg to `send_lobby_chat_message`
* changed the return type from `bool` to `Result<(), SteamError>
* added documentation adapted from the steamworks docs page
* fixed an error regarding an unrelated if statement (feel free to revert)

Implement wrapper for SendLobbyChatMsg

---

src/matchmaking.rs

closes #140 
added 7 functions for filtering out lobby requests:
* `set_lobby_list_filter`: adds filters defined in a `LobbyListFilter` struct.
* `set_request_lobby_list_string_filter`: adds filters for key value pairs of strings.
* `set_request_lobby_list_numerical_filter`: adds filters for key value pairs of string number types.
* `set_request_lobby_list_near_value_filter`: adds sorting based on which value is closer to the filter
* `set_request_lobby_list_distance_filter`: adds filtering based on geographical distance
* `set_request_lobby_list_slots_available_filter`: adds filtering based on how many open slots a lobby has
* `set_request_lobby_list_result_count_filter`: adds the maximum number of results a request can resolve to.
added 1 struct:
* `LobbyListFilter`: struct that holds …

Add lobby list request filtering

---

README.md
examples/achievements/Readme.md
src/user_stats.rs
src/user_stats/stats.rs

Added multiple new achievement API functions:
```rust
// Non-working example
client.user_stats().request_global_achievement_percentages(move|result|{
client.user_stats().achievement(name).get_achievement_achieved_percent().unwrap(); // -> Result<f32,()>
});
client.user_stats().achievement(name).get_achievement_display_attribute("name" | "desc" | "hidden").unwrap(); // -> Result<&str,()>
client.user_stats().achievement(name).get_achievement_icon().unwrap(); // -> Option<Vec<u8>>
```
Full usage examples of all new API functions can be found in `examples/achievements/Readme.md`.

Added multiple Achievement API functions

---

src/networking_sockets.rs

* Add error handling to `receive_messages`
* Add `get_authentication_status`
* Add `run_callbacks`

Networking improvements

---

src/error.rs

[Update SDK to 1.58a ](https://github.com/Noxime/steamworks-rs/pull/151#issue-2080674354)  has a code error, will cause the program to crash when throwing SteamAPIInitError.
This PR fixed it.

Fix fatal error of `SteamAPIInitError::from_result_and_message`.

---

src/ugc.rs

These two field are particularly useful for the user's UGC list.

Add `time_added_to_user_list` and `visibility` for ugc QueryResult.

---

src/server.rs

This would be useful for me, as I include `ServerMode` in a `Config` object that derives those traits

Add extra derive bounds to ServerMode

---

src/networking_types.rs

It seems impossible to provide a float NetworkingConfigValue because of a bug in the assert function

Incorrect assert in networking_types

---

src/user_stats/stats.rs

This PR tries to avoid the library panicking if a achievement doesn't have the proper size by returning None instead
This helps with #172 although I don't think it fully fixes it as a permanent fix should include returning any achievement (possibly in a V2 function returning a more complex struct)

fix: remove unnecesary panic when checking achievement icon size

---

src/networking_sockets.rs
src/networking_sockets_callback.rs
src/networking_types.rs

I encountered a problem where sometimes my server would panic for no apparent reason. 
The panic happened in TryFrom<i32> for NetConnectionEnd. I'm not quite sure why I added a panic in a `try_from` implementation in my original PR. I think that was simply an oversight on my part.
After looking at NetConnectionEnd again it seemed like a better idea to create a fallback `Other` type in case new types get added in the future. I also made it possible to customize app end reasons.

Change NetConnectionEnd to be closer to ESteamNetConnectionEnd

---

src/ugc.rs

This adds the "file_name" field to QueryResult. 
AFAIK, this field is empty in modern games, but it's needed to manage workshop items in older games.
For example, in Total War: Shogun 2, mods are ".pack" files. When uploaded, they get wrapped into a ".bin" file with a random name. When you subscribe to them, the ".bin" file is downloaded, and you need this field to know what the original name of the file was.

Add file_name field to QueryResult.

---

src/lib.rs
src/screenshots.rs

Hey! We needed the ability to pass custom screenshots to Steam, so I've implemented parts of the `ISteamScreenshots` API:
- `HookScreenshots`
- `IsScreenshotsHooked`
- `AddScreenshotToLibrary`
- `TriggerScreenshot`
- `ScreenshotReady_t` callback
- `ScreenshotRequested_t` callback
I've tested all but `TriggerScreenshot` in our game, and `TriggerScreenshot` is trivial, so it should all work :)
Hope this is useful, and thanks for the crate!

Basic screenshots API

---

src/friends.rs

Had some issues using this, would cause status access violations. Returns a null pointer if not found and needs to be checked.
[Steamworks API - GetPlayerNickname](https://partner.steamgames.com/doc/api/ISteamFriends#GetPlayerNickname)

fix(friends): add null check to nick_name

---

src/input.rs

Adds show_binding_panel from the Steam Input API.
Tested on macOS with steamworks sdk version 1.59.

Add binding for show_binding_panel

---

src/utils.rs

add implementation for SteamAPI_ISteamUtils_IsOverlayEnabled() at client.utils().is_overlay_enabled()

implementation for SteamAPI_ISteamUtils_IsOverlayEnabled

---

src/input.rs

Return value for the call to SteamAPI_ISteamInput_Init was not properly forwarded.
Fixed the call so users can check if the SteamInput system has been properly initialized or not.

fix call to SteamAPI_ISteamInput_Init

---

src/lib.rs

Adds functions:
* steam_api_init_flat() : wrapper for the SDK call,
* init_flat() : copy of init(), but calls steam_api_init_flat() instead of steam_api_init_ex(),
* init_flat_app() : copy of init_app(), but calls init_flat() instead of init(),

adds implementation for SteamAPI_InitFlat

---

Cargo.toml
examples/lobby/Cargo.toml
examples/lobby/src/main.rs
src/matchmaking.rs

* `LobbyChatMsg` callback, used to receive messages from matchmaking lobbies send by `matchmaking.send_lobby_chat_msg`.
* `get_lobby_chat_entry` function, used to receiver message buffers from `LobbyChatMsg` callback.
* Simple example `lobby` to demonstrate this functionality.
* `LobbyChatMsg_t`: https://partner.steamgames.com/doc/api/ISteamMatchmaking#LobbyChatMsg_t
* `GetLobbyChatEntry`: https://partner.steamgames.com/doc/api/ISteamMatchmaking#GetLobbyChatEntry 
Please let me know what if there is anything I'm missing, this is my first time contributing to this repo :)

Adds LobbyChatMsg callback and get_lobby_chat_entry function

---

src/lib.rs
src/matchmaking.rs
src/networking_messages.rs
src/networking_sockets.rs
src/networking_types.rs
src/networking_utils.rs
src/remote_storage.rs
src/server.rs
src/user.rs
src/user_stats.rs

Closes: https://github.com/Noxime/steamworks-rs/issues/159
The tests do not run for me, neither on main nor on this branch. I get a bunch of timeouts like these:
```
test matchmaking::test_lobby has been running for over 60 seconds
test networking_sockets::tests::test_create_listen_socket_ip has been running for over 60 seconds
test networking_sockets::tests::test_socket_connection has been running for over 60 seconds
test networking_types::tests::test_allocate_and_free_message has been running for over 60 seconds
test networking_utils::tests::test_get_networking_status has been running for over 60 seconds
test remote_storage::test_cloud has been running for over 60 seconds
```
I am also confused about this text in the Steam docs, referenced by @james7132 in the above issue:
> …

Remove SingleClient

---

src/networking_messages.rs
src/networking_utils.rs

I need to access these callbacks for a bevy integration of steamworks-rs so I made them public.

Made all callbacks public

---

src/lib.rs
src/timeline.rs

I've added supports for the latest steamworks beta feature ISteamTimeline which permits to add event to the Steam Record timeline, like kills, death etc.
https://partner.steamgames.com/doc/features/timeline
https://store.steampowered.com/gamerecording

Add ISteamTimeline supports

---

Cargo.toml
examples/networking-messages/Cargo.toml
examples/networking-messages/README.md
examples/networking-messages/src/main.rs
src/matchmaking_servers.rs
src/networking_messages.rs

Previously, the session got accepted but immediately closed because of the convenience drop impl. Perhaps we should not have this style of auto close?
The example is very simple atm, but is better than anything.

Fix NetworkingMessages accepting and add an example

---

src/matchmaking.rs

Previously, the `steamworks::StringFilterKind` enum lacked the exhaustive filter options exposed by the Steamworks API, only exposing `k_ELobbyComparisonEqual` and `k_ELobbyComparisonNotEqual`, quite confusingly, as `StringFilterKind::Include` and `StringFilterKind::Exclude` respectively. I have patched these into the enum.
```rust
...
match filter {
StringFilterKind::EqualToOrLessThan=> sys::ELobbyComparison::k_ELobbyComparisonEqualToOrLessThan,
StringFilterKind::LessThan=> sys::ELobbyComparison::k_ELobbyComparisonLessThan,
StringFilterKind::Equal=> sys::ELobbyComparison::k_ELobbyComparisonEqual,
StringFilterKind::GreaterThan=> sys::ELobbyComparison::k_ELobbyComparisonGreaterThan,
StringFilterKind::EqualToOrGreaterThan=> sys::ELobbyComparison::k_ELobbyComparisonEqualToOrGreaterThan, …
```

Add StringFilterKind exhaustive filters

---

src/server.rs

set_advertise_server_active
set_password_protected
set_bot_player_count

fix(server.rs)Add functions that have already been extern "C"

---

src/user_stats.rs

Added RequestUserStats to work around deprecation of RequestCurrentStats from the last client update.

Add request user stats

---

src/matchmaking.rs

Address lifetime concern in lobby_data.  Also silently ignore utf8 errors because I'd rather a bad actor not crash the game.
This is a breaking change.

change lobby_data to return an owned string

---

src/matchmaking.rs

I added functions to get and set lobby member data.
https://partner.steamgames.com/doc/api/ISteamMatchmaking#GetLobbyMemberData
https://partner.steamgames.com/doc/api/ISteamMatchmaking#SetLobbyMemberData
This addresses the feedback from #221 
I meant to force push the branch and deleted instead 🤣. Been a long day.

add lobby member data functions

---

.github/workflows/ci.yml
Cargo.toml
src/friends.rs
src/lib.rs
src/networking_types.rs
src/ugc.rs
src/utils.rs

This PR updates several outdated dependencies (bitflags, serde_test, thiserror) and removes a now unnecessary dependency on lazy_static.
lazy_static is no longer needed as `RwLock::new` is now const as of Rust 1.63.
Also updated and fixed up the CI checks.

chore: Update and cleanup dependencies

---

src/matchmaking_servers.rs

Some warnings were coming up when using the latest stable Rust regarding missing a specified ABI for extern functions. This resolves them.

chore: Resolve missing extern ABI warnings

---

src/friends.rs

Remove the unnecessary asserts in `friends.rs` as the API might return images that are off-by-one. Resolves #231.

Remove unnecessary asserts

---

src/callback.rs
src/friends.rs
src/matchmaking.rs
src/networking.rs
src/networking_messages.rs
src/networking_types.rs
src/networking_utils.rs
src/remote_play.rs
src/screenshots.rs
src/ugc.rs
src/user.rs
src/user_stats/stat_callback.rs
src/utils.rs

The documentation for `CallbackHandle` says it removes the callback on dropping the the handle. This is not true. CallbackHandle does not implement `Drop`, instead relying on `CallbackHandle::disconnect` instead, which also does not take ownership of the handle.
This PR implements Drop for CallbackHandle, and removes `CallbackHandle::disconnect`. This is a breaking change.
As this is a breaking change, might as well remove the unused `SIZE` associated constant on the `Callback` trait.

Properly implement Drop for CallbackHandle

---

src/app.rs
src/callback.rs
src/friends.rs
src/input.rs
src/lib.rs
src/matchmaking.rs
src/matchmaking_servers.rs
src/networking.rs
src/networking_messages.rs
src/networking_sockets.rs
src/networking_sockets_callback.rs
src/networking_types.rs
src/networking_utils.rs
src/remote_play.rs
src/remote_storage.rs
src/screenshots.rs
src/server.rs
src/timeline.rs
src/ugc.rs
src/user.rs
src/user_stats.rs
src/user_stats/stats.rs
src/utils.rs

The `Manager` generic type param is prolific, it's everywhere in the codebase, but it really only comes down to only a single, non-performance sensitive call in `run_callbacks`, which is more of an implementation detail than anything else, but is surfaced on the consumer facing API. This makes the code harder to read, maintain, and consume.
This PR...
*  Makes the Manager trait and types all private, object-safe, and a safe trait.
*  Removes the generics on all of the types that really didn't need them.
* Made the Manager field on the inner state a trait object instead, calling it over a static dispatch on the type in `run_callbacks`.
* Moves some of the `unsafe impl`s for Send/Sync on top level types to lower level ones where appropriate. This is done to rely more on Send/Sync …

Remove unnecessary generics

---

src/callback.rs
src/lib.rs

Resolves #125. Implements `Client::process_callbacks` that allows taking a non-'static and/or non-Send function to handle callbacks instead of relying on handlers stored in `Callbacks`.

Client::process_callbacks as a way to work with non-Send/'static callback handlers

---

src/matchmaking.rs

- Implemented `set_lobby_game_server()` and `get_lobby_game_server()` methods for Matchmaking service
- Added comprehensive unit tests covering both methods
- Followed existing code style patterns
- All new tests pass successfully
- Verified integration with existing Matchmaking functionality
@Noxime @ceifa Please review when you have time. Thanks!

feat: Add set_lobby_game_server and get_lobby_game_server to Matchmaking

---

src/callback.rs
src/friends.rs
src/lib.rs
src/matchmaking.rs
src/networking.rs
src/server.rs
src/ugc.rs
src/user.rs
src/user_stats.rs
src/user_stats/stat_callback.rs
src/utils.rs

This partially addresses #253 by splitting the Mutex on Callbacks between the callbacks and the call results, which should resolve the deadlocks seen with #253.
As a separate cleanup, the unused parameter on `register_call_result` was removed.

Split the Mutex on Callbacks

---

src/callback.rs
src/error.rs
src/friends.rs
src/lib.rs
src/matchmaking.rs
src/matchmaking_servers.rs
src/networking.rs
src/networking_messages.rs
src/networking_types.rs
src/networking_utils.rs
src/remote_play.rs
src/remote_storage.rs
src/screenshots.rs
src/server.rs
src/ugc.rs
src/user.rs
src/user_stats.rs
src/user_stats/stat_callback.rs
src/user_stats/stats.rs
src/utils.rs

When handling callbacks and call results, we're turning the provided pointers into references without validating that the pointer is aligned for the type, which [according to the reference](https://doc.rust-lang.org/std/ptr/index.html#pointer-to-reference-conversion) is an unsound use of ùnsafe`.
This PR uses [`ptr::read_unaligned`](https://doc.rust-lang.org/std/ptr/fn.read_unaligned.html) to avoid this issue. This could result in a bit of a performance regression, but avoids any undefined behavior regardless of what the Steam SDK does.
This PR also cleans up a lot of the unnecessary pointer casting.

Use unaligned reads to read callbacks and call results to avoid undefined behavior

---

src/lib.rs
src/server.rs

Why thou needeth a full virtual dispatch table, when a humble enumeration will do the trick?

Change Manager from a trait to an enum

---

src/app.rs
src/callback.rs
src/lib.rs

I had to move the `#[macro_use] mod callback;` section above the `mod app;` in order for the `impl_callback!` macro to work. Other than that I essentially copied everything from the `SteamServersConnected`, as that was the only callback without any extra parameters just like this one.
I tested this locally using an [updated version of steamworks.js](https://github.com/ceifa/steamworks.js/pull/196) in an electron app, and everything seems to work.

Add NewUrlLaunchParameters callback
